#pragma once

#include "Ports_init.hpp"
#include "emc.hpp"
#include "Timers_init.hpp"
#include "AdcStorage.hpp"
#include "dIOStorage.hpp"
#include "IntPriority.hpp" 
#include "controllerDMA.hpp"
#include "terminalUartDriver.hpp"

#include "i_adc.hpp"
#include "din_cpu.hpp"
#include "set_spi.hpp"
#include "spi_ports.hpp"
#include "adc.hpp"
#include "rtc.hpp"
#include "dac.hpp"
#include "mb_slave.hpp" 
#include "set_uart.hpp"